# Generated by Django 6.1.1 on 2026-09-22 07:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Radnik',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ime', models.CharField(max_length=100)),
                ('prezime', models.CharField(max_length=100)),
                ('oib', models.CharField(max_length=11, unique=True, validators=[django.core.validators.RegexValidator(message='OIB mora sadržavati točno 11 znamenki.', regex='^\\d{11}$')])),
                ('struka', models.CharField(max_length=150)),
                ('datum_rodjenja', models.DateField(blank=True, null=True)),
                ('drzavljanstvo', models.CharField(blank=True, max_length=100)),
                ('adresa', models.CharField(blank=True, max_length=255)),
                ('telefon', models.CharField(blank=True, max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('poslodavac', models.CharField(blank=True, max_length=200)),
                ('datum_zaposlenja', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('aktivan', 'Aktivan'), ('neaktivan', 'Neaktivan')], default='aktivan', max_length=20)),
                ('broj_putovnice', models.CharField(blank=True, max_length=50)),
                ('vrsta_dozvole', models.CharField(blank=True, choices=[('dozvola_boravak_rad', 'Dozvola za boravak i rad'), ('potvrda_prijava_rada', 'Potvrda o prijavi rada'), ('plava_karta_eu', 'EU plava karta'), ('ostalo', 'Ostalo')], max_length=30)),
                ('datum_izdavanja_dozvole', models.DateField(blank=True, null=True)),
                ('datum_isteka_dozvole', models.DateField(blank=True, null=True)),
                ('napomena', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Radnik',
                'verbose_name_plural': 'Radnici',
                'ordering': ['prezime', 'ime'],
            },
        ),
    ]
