# Generated by Django 6.1.1 on 2026-09-23 14:52

import django.db.models.deletion
from django.db import migrations, models


def prebaci_dozvole(apps, schema_editor):
    """Postojeće podatke o dozvoli s Radnika prebacuje u zasebnu tablicu."""
    Radnik = apps.get_model('kadrovska_zadar', 'Radnik')
    RadnaDozvola = apps.get_model('kadrovska_zadar', 'RadnaDozvola')
    for radnik in Radnik.objects.all():
        if not (radnik.vrsta_dozvole or radnik.datum_izdavanja_dozvole or radnik.datum_isteka_dozvole):
            continue
        RadnaDozvola.objects.create(
            radnik=radnik,
            vrsta=radnik.vrsta_dozvole or 'ostalo',
            datum_izdavanja=radnik.datum_izdavanja_dozvole,
            datum_isteka=radnik.datum_isteka_dozvole,
        )


def vrati_dozvole(apps, schema_editor):
    """Na Radnika vraća najnoviju dozvolu (starije se gube)."""
    RadnaDozvola = apps.get_model('kadrovska_zadar', 'RadnaDozvola')
    for dozvola in RadnaDozvola.objects.order_by('radnik_id', '-datum_isteka').distinct('radnik_id'):
        radnik = dozvola.radnik
        radnik.vrsta_dozvole = dozvola.vrsta
        radnik.datum_izdavanja_dozvole = dozvola.datum_izdavanja
        radnik.datum_isteka_dozvole = dozvola.datum_isteka
        radnik.save()


class Migration(migrations.Migration):

    dependencies = [
        ('kadrovska_zadar', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RadnaDozvola',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vrsta', models.CharField(choices=[('dozvola_boravak_rad', 'Dozvola za boravak i rad'), ('potvrda_prijava_rada', 'Potvrda o prijavi rada'), ('plava_karta_eu', 'EU plava karta'), ('ostalo', 'Ostalo')], max_length=30)),
                ('broj_dozvole', models.CharField(blank=True, max_length=50)),
                ('izdao', models.CharField(blank=True, max_length=150)),
                ('datum_izdavanja', models.DateField(blank=True, null=True)),
                ('datum_isteka', models.DateField(null=True)),
                ('napomena', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('radnik', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dozvole', to='kadrovska_zadar.radnik')),
            ],
            options={
                'verbose_name': 'Radna dozvola',
                'verbose_name_plural': 'Radne dozvole',
                'ordering': ['-datum_isteka', '-datum_izdavanja'],
            },
        ),
        migrations.RunPython(prebaci_dozvole, vrati_dozvole),
        migrations.RemoveField(
            model_name='radnik',
            name='datum_isteka_dozvole',
        ),
        migrations.RemoveField(
            model_name='radnik',
            name='datum_izdavanja_dozvole',
        ),
        migrations.RemoveField(
            model_name='radnik',
            name='vrsta_dozvole',
        ),
    ]
