# Generated by Django 6.1.1 on 2026-09-23 19:08

import django.db.models.deletion
import kadrovska_zadar.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kadrovska_zadar', '0002_radna_dozvola'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dokument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vrsta', models.CharField(choices=[('radna_dozvola', 'Radna dozvola'), ('putovnica', 'Putovnica'), ('ugovor', 'Ugovor o radu'), ('ostalo', 'Ostalo')], default='ostalo', max_length=30)),
                ('naziv', models.CharField(max_length=200)),
                ('datoteka', models.FileField(storage=kadrovska_zadar.models.privatni_storage, upload_to=kadrovska_zadar.models.putanja_dokumenta)),
                ('izvorni_naziv', models.CharField(max_length=255)),
                ('velicina', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dozvola', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dokumenti', to='kadrovska_zadar.radnadozvola')),
                ('radnik', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dokumenti', to='kadrovska_zadar.radnik')),
            ],
            options={
                'verbose_name': 'Dokument',
                'verbose_name_plural': 'Dokumenti',
                'ordering': ['-created_at'],
            },
        ),
    ]
